version: '3.9.8'

services:
  django:
    command: gunicorn mone.wsgi application --bind 0.0.0.0:8000
    build: .
    ports:
      - "8000:8000"
    volumes:
      - db_volume:/home/app/banco
      - static_volume:/home/app/static
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/static
volumes:
  db_volume:
  static_volume: